### ISSUE TITLE
Class 'bigbrush\tinypng\TinyPng' not found

### ISSUE THREAD

**Issue by Bdabest** [bigbrush/yii2-tinypng#5]
Hi there.

I've got a very odd problem. I keep getting a Class 'bigbrush\tinypng\TinyPng' not found
I've got the 'use bigbrush\tinypng\TinyPng;' along with all my other classes.
I'm calling it with:
$tiny = new TinyPng(['apiKey' => '******']);    //using a working API key
this line of code is giving me the exception with class not found. I've gone into the TinyPng.php file to see if the namespace is correct and all seems to be fine.
I've even tried just calling it with $tiny = new \bigbrush\tinypng\TinyPng(['apiKey' => '******']); to no avail.
I've installed it via composer and run the 'composer update' and reinstalled it in case it wasn't installed correctly.

Is there something else i need to add? Maybe to the config file?

**Comment by Bdabest** [comment]
Found the issue.
was an autoloader problem, just added 
 'bigbrush\\tinypng\\' => array($vendorDir . '/bigbrush/yii2-tinypng'), 
to the autoload_psr4.php file
Please consider adding this as most people just want a plug and play extension.

Thanks for a great extension, works well now.

**Comment by bigbrush** [comment]
Thanks for looking into the issue. This has been mentioned before so i will add the autoload.
